### ISSUE TITLE
TODO list before first major release with official API (v5.0)

### ISSUE THREAD

**Issue by Graeme22** [tastyware/tastytrade#19]
Now that Tasty has released the [official API documentation](https://developer.tastytrade.com), there's a lot of functionality that needs to be implemented ASAP. This is a list of the different categories in the documentation, I'd like to get them all implemented before releasing version 5.0.

- [x] Session
- [x] Account Data Streamer
- [x] Market Data Streamer
- [x] Account Status
- [x] Accounts & Customers
- [x] Balances & Positions
- [x] Instruments
- [x] Margin Requirements
- [x] Market Metrics
- [x] Net Liquidating Value History
- [x] Orders
- [x] Risk Parameters
- [x] Symbol Search
- [x] Transactions
- [x] Watchlists
- [x] readthedocs
- [x] README

Help is always welcome! Make sure any changes are well-documented and pass all tests before submitting your PR.

**Comment by pressplay21** [comment]
How do you get the live option prices? For example, "SPXW  230519C04200000" or any SPX contracts. I tried a few things but it didn't work. Maybe I'm not using it correctly.

session = Session(TT_USER,TT_PASS)
streamer = await DataStreamer.create(session)
subs_list = ['SPX'] #works
trade = await streamer.stream(EventType.TRADE, subs_list) #works

subs_list = ['SPXW  230519C04200000']
trade = await streamer.stream(EventType.TRADE, subs_list) #just hangs

subs_list = ['.SPXW230519C04200000'] 
trade = await streamer.stream(EventType.TRADE, subs_list) #just hangs

#also the option chains start from 5/19. What happened to 5/12 options?
api_url = 'https://api.cert.tastyworks.com'
option_chains_url = f'{api_url}/option-chains/SPXW'
r = requests.get(option_chains_url,headers=headers) #missing 5/12->5/19 options

**Comment by Graeme22** [comment]
Hi, that's not really related to this, please open a separate issue.

**Comment by kowkowhuang** [comment]
Looking forward to the release! Is this ready to go?

**Comment by Graeme22** [comment]
Implementing orders currently but it's a bit more complicated, shouldn't take too long though
